#!/bin/bash 
docker run -it --rm \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="$PWD:/home/appuser/workdir" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    tools:base \
    "$@"
